{
  "openapi": "3.0.0",
  "info": {
    "title": "Weather",
    "description": "",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8000",
      "description": "Local server"
    }
  ],
  "paths": {
    "/weather": {
      "post": {
        "tags": [
          "Fetch Current Weather"
        ],
        "summary": "Fetch Current Weather",
        "description": "This API fetches the current weather for a specified city and country.",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Success - Weather record was created.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "example": 201
                    },
                    "message": {
                      "type": "string",
                      "example": "Created"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "format": "uuid"
                        },
                        "city_name": {
                          "type": "string"
                        },
                        "country": {
                          "type": "string"
                        },
                        "temperature": {
                          "type": "number",
                          "format": "float"
                        },
                        "description": {
                          "type": "string"
                        },
                        "humidity": {
                          "type": "integer"
                        },
                        "wind_speed": {
                          "type": "number",
                          "format": "float"
                        },
                        "fetched_at": {
                          "type": "string",
                          "format": "date-time"
                        },
                        "created_at": {
                          "type": "string",
                          "format": "date-time"
                        },
                        "updated_at": {
                          "type": "string",
                          "format": "date-time"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Successful Creation": {
                    "summary": "A newly created weather record.",
                    "value": {
                      "code": 201,
                      "message": "Created",
                      "data": {
                        "id": "6745df6f-d768-4af5-8087-447d33cdadc9",
                        "city_name": "London",
                        "country": "GB",
                        "temperature": 18.32,
                        "description": "broken clouds",
                        "humidity": 90,
                        "wind_speed": 4.12,
                        "fetched_at": "2025-08-31T02:00:25.310923+03:30",
                        "created_at": "2025-08-31T02:00:25.315334+03:30",
                        "updated_at": "2025-08-31T02:00:25.315334+03:30"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request - No input was provided.",
            "content": {
              "application/json": {
                "examples": {
                  "No Input Provided": {
                    "value": {
                      "code": 400,
                      "message": "no input provided",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity - Request body failed validation.",
            "content": {
              "application/json": {
                "examples": {
                  "Validation Error": {
                    "value": {
                      "code": 422,
                      "message": "Unprocessable Entity",
                      "data": {
                        "CityName": "Key: 'FetchDataInput.CityName' Error:Field validation for 'CityName' failed on the 'required' tag"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found - Invalid city name.",
            "content": {
              "application/json": {
                "examples": {
                  "Invalid City": {
                    "value": {
                      "code": 404,
                      "message": "not-found",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable - Unhandled error from the weather API.",
            "content": {
              "application/json": {
                "examples": {
                  "API Error": {
                    "value": {
                      "code": 503,
                      "message": "unhandled-error",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "city_name": {
                    "type": "string"
                  },
                  "country": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Example Request": {
                  "value": {
                    "city_name": "London",
                    "country": "UK"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "List of All Weathers (Paginated)"
        ],
        "summary": "List all weather records with pagination.",
        "description": "Retrieves a paginated list of all weather records.",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Page number for pagination",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful retrieval of paginated weather data.",
            "content": {
              "application/json": {
                "examples": {
                  "Default Page (Page 1)": {
                    "value": {
                      "code": 200,
                      "message": "OK",
                      "data": {
                        "data": [
                          {
                            "id": "7876a688-b44a-4211-93f9-1f6c828a5ce7",
                            "city_name": "London",
                            "country": "GB",
                            "temperature": 17.03,
                            "description": "scattered clouds",
                            "humidity": 73,
                            "wind_speed": 3.13,
                            "fetched_at": "2025-09-01T00:19:16.421948+03:30",
                            "created_at": "2025-09-01T00:19:16.428302+03:30",
                            "updated_at": "2025-09-01T00:19:16.428302+03:30"
                          }
                        ],
                        "pagination": {
                          "total_page": 2,
                          "total_count": 12,
                          "current_page": 1
                        }
                      }
                    }
                  },
                  "Page 2": {
                    "value": {
                      "code": 200,
                      "message": "OK",
                      "data": {
                        "data": [
                          {
                            "id": "9d2ed57e-f080-419b-825b-edf65fe5b861",
                            "city_name": "",
                            "country": "",
                            "temperature": 0,
                            "description": "",
                            "humidity": 0,
                            "wind_speed": 0,
                            "fetched_at": "2025-08-31T01:48:51.979622+03:30",
                            "created_at": "2025-08-31T01:48:51.981841+03:30",
                            "updated_at": "2025-08-31T01:48:51.981841+03:30"
                          }
                        ],
                        "pagination": {
                          "total_page": 2,
                          "total_count": 12,
                          "current_page": 2
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request - Invalid page number provided.",
            "content": {
              "application/json": {
                "examples": {
                  "Invalid Page": {
                    "value": {
                      "code": 400,
                      "message": "strconv.Atoi: parsing \"asdasdasd\": invalid syntax",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/weather/latest/{city_name}": {
      "get": {
        "tags": [
          "Get Latest Weather For City"
        ],
        "summary": "Get the latest weather for a specific city.",
        "description": "Retrieves the most recent weather record for a given city.",
        "parameters": [
          {
            "name": "city_name",
            "in": "path",
            "required": true,
            "description": "The name of the city to retrieve weather for.",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful retrieval of the latest weather record.",
            "content": {
              "application/json": {
                "examples": {
                  "Success": {
                    "value": {
                      "code": 200,
                      "message": "OK",
                      "data": {
                        "id": "7876a688-b44a-4211-93f9-1f6c828a5ce7",
                        "city_name": "London",
                        "country": "GB",
                        "temperature": 17.03,
                        "description": "scattered clouds",
                        "humidity": 73,
                        "wind_speed": 3.13,
                        "fetched_at": "2025-09-01T00:19:16.421948+03:30",
                        "created_at": "2025-09-01T00:19:16.428302+03:30",
                        "updated_at": "2025-09-01T00:19:16.428302+03:30"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found - No weather record found for the city.",
            "content": {
              "application/json": {
                "examples": {
                  "Record Not Found": {
                    "value": {
                      "code": 404,
                      "message": "record not found",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/weather/{id}": {
      "get": {
        "tags": [
          "Retrieve a Single Weather"
        ],
        "summary": "Retrieve a single weather record by ID.",
        "description": "Retrieves a specific weather record using its unique ID.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "The unique ID of the weather record.",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful retrieval of a single weather record.",
            "content": {
              "application/json": {
                "examples": {
                  "Success": {
                    "value": {
                      "code": 200,
                      "message": "OK",
                      "data": {
                        "id": "87abad2b-b9c6-487c-a64b-c878490d6f1a",
                        "city_name": "Bahrain",
                        "country": "BH",
                        "temperature": 31.62,
                        "description": "few clouds",
                        "humidity": 65,
                        "wind_speed": 2.56,
                        "fetched_at": "2025-08-31T02:00:42.917452+03:30",
                        "created_at": "2025-08-31T02:00:42.919623+03:30",
                        "updated_at": "2025-08-31T02:00:42.919623+03:30"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request - Invalid ID format.",
            "content": {
              "application/json": {
                "examples": {
                  "Invalid ID": {
                    "value": {
                      "code": 400,
                      "message": "invalid UUID length: 10",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found - Weather record with the given ID does not exist.",
            "content": {
              "application/json": {
                "examples": {
                  "Record Not Found": {
                    "value": {
                      "code": 404,
                      "message": "record not found",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Update Weather"
        ],
        "summary": "Update an existing weather record by ID.",
        "description": "Updates a specific weather record with new information.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "The unique ID of the weather record to update.",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "city_name": {
                    "type": "string"
                  },
                  "country": {
                    "type": "string"
                  },
                  "temperature": {
                    "type": "number",
                    "format": "float"
                  },
                  "description": {
                    "type": "string"
                  },
                  "humidity": {
                    "type": "integer"
                  },
                  "wind_speed": {
                    "type": "number",
                    "format": "float"
                  }
                }
              },
              "examples": {
                "Example Request": {
                  "value": {
                    "city_name": "Iraq",
                    "country": "IQ",
                    "temperature": 33.6,
                    "description": "windy",
                    "humidity": 27,
                    "wind_speed": 7.2
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful update of a weather record.",
            "content": {
              "application/json": {
                "examples": {
                  "Success": {
                    "value": {
                      "code": 200,
                      "message": "OK",
                      "data": {
                        "id": "123bf444-395e-49cc-a72f-22c88c9abe39",
                        "city_name": "Iraq2",
                        "country": "IQQ",
                        "temperature": 33.2,
                        "description": "hot",
                        "humidity": 25,
                        "wind_speed": 2.2,
                        "fetched_at": "2025-08-31T02:00:47.816663+03:30",
                        "created_at": "2025-08-31T02:00:47.820679+03:30",
                        "updated_at": "2025-09-01T02:02:24.055353+03:30"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request - No input provided or invalid UUID.",
            "content": {
              "application/json": {
                "examples": {
                  "No Input": {
                    "value": {
                      "code": 400,
                      "message": "no input provided",
                      "data": null
                    }
                  },
                  "Invalid UUID": {
                    "value": {
                      "code": 400,
                      "message": "invalid UUID length: 3",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity - Request body failed validation.",
            "content": {
              "application/json": {
                "examples": {
                  "Validation Errors": {
                    "value": {
                      "code": 422,
                      "message": "Unprocessable Entity",
                      "data": {
                        "CityName": "Key: 'UpdateInput.CityName' Error:Field validation for 'CityName' failed on the 'min' tag",
                        "Country": "Key: 'UpdateInput.Country' Error:Field validation for 'Country' failed on the 'alpha' tag",
                        "Description": "Key: 'UpdateInput.Description' Error:Field validation for 'Description' failed on the 'max' tag",
                        "Humidity": "Key: 'UpdateInput.Humidity' Error:Field validation for 'Humidity' failed on the 'gte' tag",
                        "WindSpeed": "Key: 'UpdateInput.WindSpeed' Error:Field validation for 'WindSpeed' failed on the 'gte' tag"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found - Weather record with the given ID does not exist.",
            "content": {
              "application/json": {
                "examples": {
                  "Record Not Found": {
                    "value": {
                      "code": 404,
                      "message": "record not found",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Delete a Weather"
        ],
        "summary": "Delete a weather record by ID.",
        "description": "Deletes a specific weather record using its unique ID.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "The unique ID of the weather record to delete.",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful deletion of a weather record.",
            "content": {
              "application/json": {
                "examples": {
                  "Success": {
                    "value": {
                      "code": 200,
                      "message": "OK",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request - Invalid ID format.",
            "content": {
              "application/json": {
                "examples": {
                  "Invalid ID": {
                    "value": {
                      "code": 400,
                      "message": "invalid UUID length: 7",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  }
}